name: Run action on example project

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened
    paths:
      - 'tests/project/**'
      - '.github/workflows/pr_run_action.yaml'
      - 'action.yaml'
      - 'src/**'
jobs:
  run-action:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: ./
        with:
          working-directory: tests/project
