on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened
jobs:
  run-action:
    runs-on: ubuntu-latest
    name: Run action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: ./
