name: PR Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened
    paths:
      - 'tests/**/*'
      - 'src/**/*'

jobs:
  test-bats:
    name: Run BATS tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run BATS tests
        shell: bash
        working-directory: tests
        #language=bash
        run: |
          bats .
